--- #YAML:1.0
name:               MojoX-Renderer-TT
version:            0.20
abstract:           Template Toolkit renderer for Mojo
author:
    - Ask Bjørn Hansen <ask@develooper.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Mojo:        0.9
    Template:    2.18
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
