# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         MojoX-Renderer-TT
version:      0.10
version_from: lib/MojoX/Renderer/TT.pm
installdirs:  site
requires:
    Mojo:                          0.8011
    Template:                      2.18
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
