---
abstract: 'Template Toolkit renderer for Mojo'
author:
  - 'Ask Bjørn Hansen <ask@develooper.com>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101900, CPAN::Meta::Converter version 2.101670'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MojoX-Renderer-TT
requires:
  Mojo: 0.999926
  Template: 2.18
resources:
  homepage: http://search.cpan.org/dist/MojoX-Renderer-TT/
  repository: http://git.develooper.com/MojoX-Renderer-TT.git
version: 0.40
