---
abstract: 'Template Toolkit renderer for Mojo'
author:
  - 'Ask Bjørn Hansen <ask@develooper.com>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200001, CPAN::Meta::Converter version 2.101670'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MojoX-Renderer-TT
requires:
  Mojolicious: 1.3
  Template: 2.18
resources:
  bugtracker: https://github.com/abh/mojox-renderer-tt/issues
  homepage: http://search.cpan.org/dist/MojoX-Renderer-TT/
  repository: git://github.com/abh/mojox-renderer-tt.git
version: 1.13
